### ISSUE TITLE
client side(javascript) encrypt plain text  and trying to decrypt the encrypted client string at server side using  java decrypt method returns result is null

### ISSUE THREAD

**Issue by lsajjan** [themaverik/interoperable-128bit-aes-encryption#1]
Hi 
Here is my app requirement. 
we need to encrypt the user data using javascript AES 128 algorithm at client side  and  we need to decrypt the encrypted string at server side using  java code and pass the decrypted string to the web-service for further next steps .
I have used your interoperable-128bit-aes-encryption  github plugin  to achieve my requirement and here is steps i followed 

**client side javascript code i used at to encrypt the user data ** 

var KEY_SIZE = 16;
var ENCRYPTION_KEY = "thisisasamplepassphraseforencoding";

try {
  var plaintext = 'Hello World!';
  //console.log("Plain text: " + plaintext);
	
  // Ensure that the key is no more than 16-bytes long
   key = (ENCRYPTION_KEY.length > KEY_SIZE ) ? ENCRYPTION_KEY.substr(0, KEY_SIZE) : ENCRYPTION_KEY;
	
  // Generate pseudo string for IV 
   iv = CryptoJS.lib.WordArray.random(8).toString();
  console.log('IV: ' + iv);	

 var encrypted=encryptTxt(plaintext,key,iv);
var javaObj=new EncryptionClass(); // creating the java object to call the decrypt method 
var decryptedTxt=decrypt(encrypted,key,iv);
console.log("decryptedTxt"+decryptedTxt); /// output is null or decrypted text is not correct // error is javax.crypto.BadPaddingException: Given final block not properly padded
} catch (error) {
  console.log('An exception occurred while encrypting plain text: ' + error.message);
}

function encryptTxt(plaintext,key,iv){
	
	//var plaintext=document.getElementById("plainText").value;
	//document.getElementById("encryptTxt").innerHTML=palinval;
	console.log("sample encryptTxt"+plaintext);
	  try {
	    var encrypted = CryptoJS.AES.encrypt(
	      plaintext,
	      CryptoJS.enc.Utf8.parse(key),
	      { 
	        mode: CryptoJS.mode.CBC, 
	        iv: CryptoJS.enc.Utf8.parse(iv), 
	        // PKCS#7 with 8-byte block size
	        padding: CryptoJS.pad.Pkcs7 
	      }
	    );
	    var encryptedTxt=encrypted.ciphertext.toString(CryptoJS.enc.Base64);
		document.getElementById("encryptTxt").innerHTML=encryptedTxt
	    return encryptedTxt;
	  } catch (error) {
	    console.log('Encryption exception in encrypt(): ' + error.message);
	  }	
}

**Server side java code** 
public class EncryptionClass{
public String decrypt(String ciphertext,byte[] key,byte[] iv) throws UnsupportedEncodingException {
	  
//	  public static int KEY_SIZE = 16;
//	public  String ENCRYPTION_KEY = "thisisasamplepassphraseforencoding";
//	  
	  
	 // System.out.println("ciphertext--"+ciphertext);
      //System.out.println("passphrase--" +key);
      //System.out.println("ivv--" +iv);
      
      //byte[] iv = generateInitializationVector(KEY_SIZE);
      //System.out.println("IV: " + new String(iv, "UTF-8"));
      
	 // passphrase = (ENCRYPTION_KEY.length() > KEY_SIZE) ? ENCRYPTION_KEY.substring(0, KEY_SIZE) : ENCRYPTION_KEY;
      //byte[] key = passphrase.getBytes("UTF-8");
     // byte[] iv=ivv.getBytes("UTF-8");
      // Generate initialization vector 
     // byte[] iv = generateInitializationVector(KEY_SIZE);
      
      //System.out.println("iv--"+iv);
      //System.out.println("key--" +key);
      //System.out.println("ciphertext--" +ciphertext);
	  
    try {
      SecretKeySpec secretKeySpec;
      secretKeySpec = new SecretKeySpec(key, "AES");
      Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
      AlgorithmParameters algorithmParams = AlgorithmParameters.getInstance("AES");
      algorithmParams.init(new IvParameterSpec(iv));
      cipher.init(Cipher.DECRYPT_MODE, secretKeySpec, algorithmParams);
      String decryptedtext1=new String(cipher.doFinal(DatatypeConverter.parseBase64Binary(ciphertext)), "UTF-8");
      System.out.println("decryptedtext1"+decryptedtext1);
      return new String(cipher.doFinal(DatatypeConverter.parseBase64Binary(ciphertext)), "UTF-8");
    } catch (NoSuchPaddingException | BadPaddingException e) {
      System.out.println("Padding exception in decrypt(): " + e);
    } catch ( NoSuchAlgorithmException | InvalidKeyException	| IllegalBlockSizeException e ) {
      System.out.println("Validation exception in decrypt(): " + e);
    } catch (Exception e) {
      System.out.println("Exception in decrypt(): " + e);
    }
    return null;
  }
}

Please help me out how we can achieve accurate result as per our requirements, it would be grateful thanks in advance

**Comment by themaverik** [comment]
Try testing the separately first. Lets say I test encryption and decryption using CryptoJS. See what output the encryption produces. And also keep in mind if you decrypt, you will need to use the same IV that has been used during encryption.

You need to modify your code as follows:
`
//Client-side js:

var KEY_SIZE = 16;
var ENCRYPTION_KEY = "thisisasamplepassphraseforencoding";

try {
  var plaintext = 'Hello World!';
  console.log("Plain text: " + plaintext);

  // Ensure that the key is no more than 16-bytes long
  key = (ENCRYPTION_KEY.length > KEY_SIZE ) ? ENCRYPTION_KEY.substr(0, KEY_SIZE) : ENCRYPTION_KEY;

  // Generate pseudo string for IV
  iv = CryptoJS.lib.WordArray.random(8).toString();
  console.log('IV: ' + iv);

  var encrypted = encryptTxt(plaintext,key,iv);
  console.log("Encrypted text: " + encrypted);
} catch (error) {
  console.log('An exception occurred while encrypting plain text: ' + error.message);
}

function encryptTxt(plaintext,key,iv){

  //var plaintext=document.getElementById("plainText").value;
  //document.getElementById("encryptTxt").innerHTML=palinval;
  console.log("sample encryptTxt: " + plaintext);
  try {
    var encrypted = CryptoJS.AES.encrypt(
      plaintext,
      CryptoJS.enc.Utf8.parse(key),
      { 
        mode: CryptoJS.mode.CBC, 
        iv: CryptoJS.enc.Utf8.parse(iv), 
        // PKCS#7 with 8-byte block size
        padding: CryptoJS.pad.Pkcs7 
      }
    );
    var encryptedTxt=encrypted.ciphertext.toString(CryptoJS.enc.Base64);
	//document.getElementById("encryptTxt").innerHTML=encryptedTxt
    return encryptedTxt;
  } catch (error) {
    console.log('Encryption exception in encrypt(): ' + error.message);
  }	
}

//Server side (Java):

class EncryptionClass {

    public final static int    KEY_SIZE       = 16;
    public final static String ENCRYPTION_KEY = "thisisasamplepassphraseforencoding";

    public static void main(String[] args) {
        try {
            // encrypted text received abkfuLRvokL7SBXmoGXtrg== (received from front-end e.g as ajax)
            // iv parameter used during encryption -> c2e38e3c5a2e899d (needs to be the same as the one used in
            // encryption)
            // secret encryption key -> ENCRYPTION_KEY

            decrypt("abkfuLRvokL7SBXmoGXtrg==", ENCRYPTION_KEY, "c2e38e3c5a2e899d");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    public static String decrypt(String ciphertext, String key, String iv) throws UnsupportedEncodingException {

        System.out.println("ciphertext--" + ciphertext);
        System.out.println("passphrase--" + key);
        System.out.println("IV: " + iv);

        try {
            SecretKeySpec secretKeySpec;

            // trim key length & iv parameters
            key = (key.length() > 16) ? key.substring(0, 16) : key;
            iv = (iv.length() > 16) ? iv.substring(0, 16) : iv;

            secretKeySpec = new SecretKeySpec(key.getBytes(), "AES"); // key in bytes
            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
            AlgorithmParameters algorithmParams = AlgorithmParameters.getInstance("AES");
            algorithmParams.init(new IvParameterSpec(iv.getBytes())); // iv in bytes
            cipher.init(Cipher.DECRYPT_MODE, secretKeySpec, algorithmParams);
            String decryptedtext1 = new String(cipher.doFinal(DatatypeConverter.parseBase64Binary(ciphertext)), "UTF-8");
            System.out.println("decryptedtext1" + decryptedtext1);
            return new String(cipher.doFinal(DatatypeConverter.parseBase64Binary(ciphertext)), "UTF-8");
        } catch (NoSuchPaddingException | BadPaddingException e) {
            System.out.println("Padding exception in decrypt(): " + e);
        } catch (NoSuchAlgorithmException | InvalidKeyException | IllegalBlockSizeException e) {
            System.out.println("Validation exception in decrypt(): " + e);
        } catch (Exception e) {
            System.out.println("Exception in decrypt(): " + e);
        }
        return null;
    }
}
`

You can refer to this blog [post](https://lamteiwahlang.wordpress.com/2017/04/09/inter-operable-aes-encryption/) for detailed description.

**Comment by lsajjan** [comment]
Thanks for your ans, i have one more question that how we can use random secret key generator for encryption at client side as well as server side (java code) for decryption of encrypted text

**Comment by themaverik** [comment]
You can you anything for that as long as you use the same key for encryption and decryption. The idea is not to expose your secret key, hence why you need to encrypt in the first place. So every time you encrypt, you use the same key for decryption, but along with the encryption key, you generate an iv vector that will also be used in the encryption process. This iv should be random and should change every time you run the encryption. The example uses cbc mode for encryption. You can find more about it [here](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation).
